# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='operate',
            field=models.CharField(choices=[(1, '购买'), (2, '加入购物车')], default=None, max_length=10, verbose_name='操作'),
        ),
        migrations.AddField(
            model_name='userlog',
            name='ptime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='商品上传时间'),
            preserve_default=False,
        ),
    ]
