# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0002_auto_20190819_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='goods_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsIssue.Goods', verbose_name='用户发布的商品名称'),
        ),
    ]
