# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 09:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='商品名称')),
                ('price', models.FloatField(default=None, verbose_name='商品价格')),
                ('discount', models.FloatField(default=None, verbose_name='商品折扣')),
                ('status', models.IntegerField(choices=[(1, '在售'), (2, '缺货'), (3, '下架')], default=None, verbose_name='商品状态')),
                ('ptime', models.DateTimeField(auto_now=True, verbose_name='上架时间')),
                ('context', models.TextField(default=None, help_text='这是商品简介，请不要超过100个字', verbose_name='商品描述')),
                ('img', models.ImageField(default='goods/beauty_1.jpg', upload_to='goods/', verbose_name='商品图片')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='商品拥有者')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'permissions': (('can_change_goods_status', '可以修改商品状态'), ('can_add_goods', '可以添加商品')),
            },
        ),
    ]
