# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsIssue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='img',
            field=models.ImageField(default='goods/beauty_1.jpg', upload_to='goods/%Y%m%d', verbose_name='商品图片'),
        ),
    ]
