# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodsIssue', '0002_auto_20190820_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='discount',
        ),
    ]
